init commit

diff --git a/.github/workflows/app.yml b/.github/workflows/app.yml
--- a/.github/workflows/app.yml
+++ b/.github/workflows/app.yml
@@ -50,7 +50,7 @@ jobs:
 
   backend-build:
     name: Backend Build
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
     timeout-minutes: 90
     permissions:
       contents: write
@@ -58,6 +58,21 @@ jobs:
     env:
       NODE_VERSION: 21.6.0
       SPRING_OUTPUT_ANSI_ENABLED: DETECT
+    defaults:
+      run:
+        shell: bash
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ ubuntu-latest, macos-latest ]
+        java-version: [ '21' ]
+        include:
+          - os: ubuntu-latest
+            executable-suffix: ''
+            native-build-args: --verbose -J-Xmx10g
+          - os: macos-latest
+            executable-suffix: ''
+            native-build-args: --verbose -J-Xmx13g
     steps:
       # Set up swap space for Linux
       - name: Set up swap space
@@ -65,6 +80,16 @@ jobs:
         uses: pierotofy/set-swap-space@v1.0
         with:
           swap-size-gb: 10
+
+      # Set up Docker for macOS
+      - name: 'SETUP: docker'
+        run: |
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          #echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          #while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+        if: runner.os == 'macOS'
 
       # Checkout the repository
       - name: Checkout Repository
@@ -85,12 +110,12 @@ jobs:
           cache-dependency-path: src/main/webapp/package-lock.json
 
       # Set up Java Development Kit (JDK) and GraalVM
-      - name: Set up JDK 21 with GraalVM
+      - name: Set up GraalVM (Java ${{ matrix.java-version }})
         uses: graalvm/setup-graalvm@v1
         with:
           distribution: 'liberica'
           version: '22.3.0'
-          java-version: '21'
+          java-version: '${{ matrix.java-version }}'
           components: 'native-image'
           github-token: ${{ secrets.GITHUB_TOKEN }}
           cache: 'maven'
@@ -132,10 +157,6 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Log in to Docker Registry
-        run: |
-          docker login https://registry-1.docker.io -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
-
       # Build Docker image
       - name: Build Docker Image
         run: |
@@ -154,4 +175,4 @@ jobs:
             -Ddocker.publish.username=${{ secrets.DOCKER_USERNAME }} \
             -Ddocker.publish.password=${{ secrets.DOCKER_PASSWORD }} \
             -Dspring-boot.build-image.imageName=docker.io/${{ secrets.DOCKER_USERNAME }}/spring-nextjs-app:${{ github.ref_name }}-native \
-            -Dnative-build-args="--verbose -J-Xmx10g"
+            -Dnative-build-args=${{ matrix.native-build-args }}
